# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificaton', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=80)),
                ('percentage', models.IntegerField()),
                ('year_of_passing', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=2)),
                ('dob', models.DateField()),
                ('grade', models.CharField(max_length=20)),
                ('date_of_join', models.DateField()),
                ('role', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Address')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='experience',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
    ]
