# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_type', models.CharField(max_length=2)),
                ('House_No', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=30)),
                ('qualificaton', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('office', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=2)),
                ('dob', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
                ('p_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='student.Address')),
                ('parent_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ParentInfo')),
                ('t_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_address', to='student.Address')),
            ],
        ),
    ]
