# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_classinfo_class_teacher'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.ClassInfo'),
            preserve_default=False,
        ),
    ]
